{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.services.authelia-custom;

  # Default users file with argon2id hashed password for "changeme"
  defaultUsersFile = pkgs.writeText "authelia-users.yml" ''
    users:
      admin:
        displayname: "Administrator"
        password: "$argon2id$v=19$m=65536,t=3,p=4$Wx/gEuHxBpXRPCRZxiw5gA$pPk3/tRqSxnrwbq9YxGes49B/GstlPzzSQdRz9wMvR8"
        email: admin@${cfg.domain}
        groups:
          - admins
  '';
in
{
  options.services.authelia-custom = {
    enable = mkEnableOption "Authelia SSO service";

    domain = mkOption {
      type = types.str;
      default = config.services.caddy-custom.domain;
      description = "Base domain for Authelia";
    };

    port = mkOption {
      type = types.port;
      default = 9091;
      description = "Port for Authelia service";
    };

    usersFile = mkOption {
      type = types.path;
      default = defaultUsersFile;
      description = "Path to users.yml file for authentication";
    };

    oidc = {
      enable = mkOption {
        type = types.bool;
        default = true;
        description = "Enable OIDC provider for services like Grafana";
      };
    };

    secrets = {
      jwtSecretFile = mkOption {
        type = types.path;
        default = "/persist/secrets/authelia/jwt-secret";
        description = "Path to JWT secret file";
      };

      storageEncryptionKeyFile = mkOption {
        type = types.path;
        default = "/persist/secrets/authelia/storage-encryption-key";
        description = "Path to storage encryption key file";
      };

      sessionSecretFile = mkOption {
        type = types.path;
        default = "/persist/secrets/authelia/session-secret";
        description = "Path to session secret file";
      };

      oidcHmacSecretFile = mkOption {
        type = types.path;
        default = "/persist/secrets/authelia/oidc-hmac-secret";
        description = "Path to OIDC HMAC secret file";
      };

      oidcIssuerPrivateKeyFile = mkOption {
        type = types.path;
        default = "/persist/secrets/authelia/oidc-issuer-key.pem";
        description = "Path to OIDC issuer private key file";
      };
    };
  };

  config = mkIf cfg.enable {
    services.authelia.instances.main = {
      enable = true;

      settings = {
        theme = "dark";
        default_2fa_method = "totp";

        server = {
          address = "tcp://127.0.0.1:${toString cfg.port}";
        };

        log = {
          level = "info";
          format = "text";
        };

        totp = {
          issuer = "authelia.${cfg.domain}";
          period = 30;
          skew = 1;
        };

        authentication_backend = {
          password_reset.disable = false;
          refresh_interval = "5m";

          file = {
            path = cfg.usersFile;
            password = {
              algorithm = "argon2";
              argon2 = {
                variant = "argon2id";
                iterations = 3;
                memory = 65536;
                parallelism = 4;
                key_length = 32;
                salt_length = 16;
              };
            };
          };
        };

        session = {
          name = "authelia_session";
          cookies = [
            {
              domain = cfg.domain;
              authelia_url = "https://auth.${cfg.domain}";
              same_site = "lax";
            }
          ];
          expiration = "12h";
          inactivity = "1h";
          remember_me = "1M";
        };

        regulation = {
          max_retries = 5;
          find_time = "2m";
          ban_time = "5m";
        };

        storage = {
          local = {
            path = "/var/lib/authelia-main/db.sqlite3";
          };
        };

        notifier = {
          disable_startup_check = true;
          filesystem = {
            filename = "/var/lib/authelia-main/notifications.txt";
          };
        };

        access_control = {
          default_policy = "deny";

          rules = [
            # Authelia portal itself is public
            {
              domain = [ "auth.${cfg.domain}" ];
              policy = "bypass";
            }

            # All other services require authentication
            {
              domain = [ "*.${cfg.domain}" ];
              policy = "one_factor";
            }
          ];
        };

        identity_providers = mkIf cfg.oidc.enable {
          oidc = {
            # Note: jwks is automatically generated by the NixOS module
            # from oidcIssuerPrivateKeyFile in the secrets section
            lifespans = {
              access_token = "1h";
              authorize_code = "1m";
              id_token = "1h";
              refresh_token = "90m";
            };

            enable_client_debug_messages = false;

            clients = [
              # Grafana OIDC client
              {
                client_id = "grafana";
                client_name = "Grafana";
                client_secret = "$pbkdf2-sha512$310000$uOrqP.ms1t08cqrDAooixg$giuLEFgLzyxZSDRhnNeHmmqKWZkwLWQkLPiN5dsr4Z9SuIshFEfib6UTWIQV15/7qZjj/wlLbfOc7Rinj9C9yQ";
                public = false;
                authorization_policy = "one_factor";
                token_endpoint_auth_method = "client_secret_post";
                redirect_uris = [
                  "https://grafana.${cfg.domain}/login/generic_oauth"
                ];
                scopes = [
                  "openid"
                  "profile"
                  "groups"
                  "email"
                ];
                userinfo_signed_response_alg = "none";
              }

              # Nextcloud OIDC client
              {
                client_id = "nextcloud";
                client_name = "Nextcloud";
                client_secret = "$pbkdf2-sha512$310000$uOrqP.ms1t08cqrDAooixg$giuLEFgLzyxZSDRhnNeHmmqKWZkwLWQkLPiN5dsr4Z9SuIshFEfib6UTWIQV15/7qZjj/wlLbfOc7Rinj9C9yQ";
                public = false;
                authorization_policy = "one_factor";
                token_endpoint_auth_method = "client_secret_post";
                redirect_uris = [
                  "https://nextcloud.${cfg.domain}/apps/oidc_login/oidc"
                ];
                scopes = [
                  "openid"
                  "profile"
                  "groups"
                  "email"
                ];
                userinfo_signed_response_alg = "none";
              }

              # Immich OIDC client
              {
                client_id = "immich";
                client_name = "Immich";
                client_secret = "$pbkdf2-sha512$310000$uOrqP.ms1t08cqrDAooixg$giuLEFgLzyxZSDRhnNeHmmqKWZkwLWQkLPiN5dsr4Z9SuIshFEfib6UTWIQV15/7qZjj/wlLbfOc7Rinj9C9yQ";
                public = false;
                authorization_policy = "one_factor";
                token_endpoint_auth_method = "client_secret_post";
                redirect_uris = [
                  "https://immich.${cfg.domain}/auth/login"
                  "https://immich.${cfg.domain}/user-settings"
                  "app.immich:/"
                ];
                scopes = [
                  "openid"
                  "profile"
                  "email"
                ];
                userinfo_signed_response_alg = "none";
              }

              # Paperless OIDC client
              {
                client_id = "paperless";
                client_name = "Paperless-ngx";
                client_secret = "$pbkdf2-sha512$310000$uOrqP.ms1t08cqrDAooixg$giuLEFgLzyxZSDRhnNeHmmqKWZkwLWQkLPiN5dsr4Z9SuIshFEfib6UTWIQV15/7qZjj/wlLbfOc7Rinj9C9yQ";
                public = false;
                authorization_policy = "one_factor";
                token_endpoint_auth_method = "client_secret_post";
                redirect_uris = [
                  "https://paperless.${cfg.domain}/accounts/oidc/authelia/callback/"
                ];
                scopes = [
                  "openid"
                  "profile"
                  "email"
                  "groups"
                ];
                userinfo_signed_response_alg = "none";
              }

              # Home Assistant OIDC client
              {
                client_id = "homeassistant";
                client_name = "Home Assistant";
                client_secret = "$pbkdf2-sha512$310000$uOrqP.ms1t08cqrDAooixg$giuLEFgLzyxZSDRhnNeHmmqKWZkwLWQkLPiN5dsr4Z9SuIshFEfib6UTWIQV15/7qZjj/wlLbfOc7Rinj9C9yQ";
                public = false;
                authorization_policy = "one_factor";
                token_endpoint_auth_method = "client_secret_post";
                redirect_uris = [
                  "https://homeassistant.${cfg.domain}/auth/external/callback"
                ];
                scopes = [
                  "openid"
                  "profile"
                  "email"
                ];
                userinfo_signed_response_alg = "none";
              }
            ];
          };
        };
      };

      secrets = {
        jwtSecretFile = cfg.secrets.jwtSecretFile;
        storageEncryptionKeyFile = cfg.secrets.storageEncryptionKeyFile;
        sessionSecretFile = cfg.secrets.sessionSecretFile;
        oidcHmacSecretFile = mkIf cfg.oidc.enable cfg.secrets.oidcHmacSecretFile;
        oidcIssuerPrivateKeyFile = mkIf cfg.oidc.enable cfg.secrets.oidcIssuerPrivateKeyFile;
      };
    };

    # Create systemd service to generate secrets if they don't exist
    systemd.services.authelia-generate-secrets = {
      description = "Generate Authelia secrets if they don't exist";
      wantedBy = [ "multi-user.target" ];
      before = [ "authelia-main.service" ];

      script = ''
        SECRETS_DIR="/persist/secrets/authelia"
        mkdir -p "$SECRETS_DIR"
        chmod 700 "$SECRETS_DIR"

        # Generate JWT secret
        if [ ! -f "${cfg.secrets.jwtSecretFile}" ]; then
          echo "Generating JWT secret..."
          ${pkgs.openssl}/bin/openssl rand -base64 64 > "${cfg.secrets.jwtSecretFile}"
          chmod 600 "${cfg.secrets.jwtSecretFile}"
        fi

        # Generate storage encryption key
        if [ ! -f "${cfg.secrets.storageEncryptionKeyFile}" ]; then
          echo "Generating storage encryption key..."
          ${pkgs.openssl}/bin/openssl rand -base64 64 > "${cfg.secrets.storageEncryptionKeyFile}"
          chmod 600 "${cfg.secrets.storageEncryptionKeyFile}"
        fi

        # Generate session secret
        if [ ! -f "${cfg.secrets.sessionSecretFile}" ]; then
          echo "Generating session secret..."
          ${pkgs.openssl}/bin/openssl rand -base64 64 > "${cfg.secrets.sessionSecretFile}"
          chmod 600 "${cfg.secrets.sessionSecretFile}"
        fi

        ${optionalString cfg.oidc.enable ''
          # Generate OIDC HMAC secret
          if [ ! -f "${cfg.secrets.oidcHmacSecretFile}" ]; then
            echo "Generating OIDC HMAC secret..."
            ${pkgs.openssl}/bin/openssl rand -base64 64 > "${cfg.secrets.oidcHmacSecretFile}"
            chmod 600 "${cfg.secrets.oidcHmacSecretFile}"
          fi

          # Generate OIDC issuer private key
          if [ ! -f "${cfg.secrets.oidcIssuerPrivateKeyFile}" ]; then
            echo "Generating OIDC issuer private key..."
            ${pkgs.openssl}/bin/openssl genrsa -out "${cfg.secrets.oidcIssuerPrivateKeyFile}" 4096
            chmod 600 "${cfg.secrets.oidcIssuerPrivateKeyFile}"
          fi
        ''}

        # Set ownership to authelia user
        chown -R authelia-main:authelia-main "$SECRETS_DIR"
      '';

      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
      };
    };

    # Ensure directories exist
    systemd.tmpfiles.rules = [
      "d /var/lib/authelia-main 0700 authelia-main authelia-main -"
      "d /persist/secrets/authelia 0700 authelia-main authelia-main -"
    ];

    # Persist Authelia data across reboots
    environment.persistence."/persist" = {
      directories = [
        {
          directory = "/var/lib/authelia-main";
          user = "authelia-main";
          group = "authelia-main";
          mode = "0700";
        }
        {
          directory = "/persist/secrets/authelia";
          user = "authelia-main";
          group = "authelia-main";
          mode = "0700";
        }
      ];
    };

    # Make authelia available in system packages for password hashing
    environment.systemPackages = [ pkgs.authelia ];
  };
}
