#!/usr/bin/env bash
set -euo pipefail

if [ -f .pre-commit-config.yaml ] && command -v pre-commit >/dev/null 2>&1; then
  pre-commit run
elif command -v nix >/dev/null 2>&1; then
  nix develop --command pre-commit run
fi
